[workspace]
members = [
  "egld-esdt-swap",
  "egld-esdt-swap/meta",
  "esdt-safe",
  "esdt-safe/meta",
  "multi-transfer-esdt",
  "multi-transfer-esdt/meta",
  "multisig",
  "multisig/meta",
  "wrapped-bridged-usdc",
  "wrapped-bridged-usdc/meta"
]
