[package]
name = "bridged-tokens-wrapper-meta"
version = "0.0.0"
authors = ["Alin Cruceat <alin.cruceat@multiversx.com>"]
edition = "2021"
publish = false

[dependencies.bridged-tokens-wrapper]
path = ".."

[dependencies.multiversx-sc-meta]
version = "0.39.5"
