name: CI

on:
  push:
      branches:
        - main
  pull_request:
        branches: [ main ]

permissions:
  pull-requests: write

jobs:
  contracts:
    name: Contracts
    uses: multiversx/mx-sc-actions/.github/workflows/contracts.yml@bridge-workaround-2023-03
    with:
      rust-toolchain: nightly-2022-10-16
      vmtools-version: v1.4.60
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
